# Generated by Django 5.0.4 on 2024-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="clinic-logos"),
        ),
    ]
