# Generated by Django 5.0.4 on 2024-06-07 13:23

from django.db import migrations


def migrate_to_category_model(apps, schema_editor):
    Category = apps.get_model("core", "Category")

    categories = [
        "Analgesics",
        "Antacids",
        "Antianxiety",
        "Antibiotics",
        "Anticoagulants",
        "Antidepressants",
        "Antihypertensives",
        "Antivirals",
        "Diuretics",
        "Antihistamines",
        "Antifungals",
        "Antipsychotics",
        "Beta Blockers",
        "Bronchodilators",
        "Contraceptives",
        "Corticosteroids",
        "Expectorants",
        "Hormone Replacement Therapy",
        "Immunosuppressants",
        "Laxatives",
        "Muscle Relaxants",
        "Sedatives",
        "Statins",
        "Stimulants",
        "Vaccines",
    ]

    for item in categories:
        category, created = Category.objects.get_or_create(name=item)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_category_product"),
    ]

    operations = [migrations.RunPython(migrate_to_category_model)]
