# Generated by Django 5.0.4 on 2024-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
