# Generated by Django 5.0.4 on 2024-06-25 07:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_order_email_sent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("Doctor", "Doctor"),
                            ("Nurse", "Nurse"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=255,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("Part Time", "Part"), ("Full Time", "Full")],
                        default="Full Time",
                        max_length=255,
                    ),
                ),
                ("working_days", models.JSONField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ClinicBranch",
        ),
    ]
