# Generated by Django 5.0.4 on 2024-06-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
