# Generated by Django 5.0.4 on 2024-06-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_patient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="last_visit",
            field=models.DateField(blank=True, null=True),
        ),
    ]
