# Generated by Django 5.0.4 on 2024-06-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_patient_last_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="medical_condition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
