# Generated by Django 5.0.4 on 2024-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_patient_medical_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
