# Generated by Django 5.0.4 on 2024-07-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_reservation_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservation_type",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Acute", "Acute"),
                    ("X-Ray", "Xray"),
                    ("CT Scan", "Ctscan"),
                    ("Check Up", "Checkup"),
                    ("Chronic", "Chronic"),
                ],
                default="General",
                max_length=255,
            ),
        ),
    ]
